deploy:
  provider: npm
  email: aorinevo@gmail.com
  api_key:
    secure: HgSxk45okn3rUMa1tfrl8t6yDCRvRNqypUX2cMXBI2Dpbng5xPY0ld259a70xZIUfd7C+dbfith4y9aSGWmoGxYRh3TKaGM33aB0VK6atrxWX7i8MMCa7BVmyHw9F0WJ8sYMbDfSmQMtDsC3ecYVMkmlsirQQkvBtHFyPEmuPbSI1yKx7zyiwXyGcggqLce7b+8uRdXAcaOC41+g/t/Pzr2j5TslP0tyYdUSCZPtZctj16luFT1YAyfD+PZNEupa1jyc5LX20pnwBldclgIuTJuqfxkDhCwukyWR6lEnScblGoeUWPup9+GcRhfDmF41IS40L6YUO882hT+xC4/IEYi6LtglSKqS+zHZVWdxUHJAJi2Vokut6MxmtRlcgu5bcoIPhco5/QdErhduhwZek8Ap1VdrtlmrYVy67ArjCx4c6HCefCshFChG9GGFlK2NQ8K1rGHx5ZsBUyZkW+AqNrCeTHxSbcujPY7a3g9QIlhnYxWsNZZga1g0/hDXPSr5WxuJjsNdNs04NOXezJrME8iogjVdxNmydC5EL8UAtHZvzYI8sQEw6M4foN0mE9ERJmBL4DwVkdGszl52xyPeMXKcMicSUx6eTpaVNkLmgHOHtYvEJSwN/sI59Cs2Sn9cJQ4hZoxbOz9sGYHwOEp8dk2iufdVbXsYHWacX2txeMI=
language: node_js
os:
- linux
- osx
cache:
  directories:
  - node_modules
node_js:
- '8'
- '10'
