deploy:
  provider: npm
  email: aorinevo@gmail.com
  api_key:
    secure: UTFUQ+q4r2KpWoFqwNYwKKaPwYPYn+E2TXR0VjQ/1S1UHfgaRbxw/MRoGKDtoeKVnTRVQlTgQrPgjU5624Da21+zP5gmCGMKmTxI7hFQbrFojvMCCNn9BezMiPiD1c5xQyn/Rnp7l9dHceEXm/mztxIg7UC4Ln0gIV9stpXjY/IAO4N7E/ESykfGjMvULh2NsVJPRSEsz0OqmOdcn4eZJY18YUi49JHgVaK0V/uPDqyasSzSMo0oOqUv5BaRX0we5/f1Zlaz8TR3QkPDouAkQYNzHezz/srQ0w7rJxMMo5SzoRUT2hslEUnwG13txpYrxfIEnFzcjY/kL+hjKLj8bwsK4SPAfT31XnEZUAYHQ1Tgkd6xeitUCTB2tjDdhpWxZSmGzcKOgErOECDC7c4ZK9CnYy947aKuwRcdDly7izYhYgteh1qVRnmqF0JdvMMdeuXeNPuvhEPBEpshbnRx2PWQeGc/HH7JUwVCv7/RWpoFaYdGt7RhBXQUoCj2fjBmXs+2qzCXBM1JmDQxRYzYD/oco6+BXdG19QtCybhHJMw7AMAk1gJfD/c7b18EZ1GlLiXiXVZLOS2MtbUXEEheC1Fq7i2C9PTnW6QVw92RTY7Yb6TRXgpRPRxx/5P+taEymzxfdSEeUrHUxIYCPk4FlhQdtQrLOA3lvNRDVdjJB9k=

language: node_js

os:
  - linux
  - osx

cache:
  directories:
    - "node_modules"

node_js:
  - "6"
  - "8"
  - "10"
